### ISSUE TITLE
renesas.dweet.io is offline ?

### ISSUE THREAD

**Issue by rzr** [buglabs/Synergy-Starter-Kit#2]
Can board still be used even if its cloud part is gone ?

https://renesas.dweet.io/

**Comment by mpeddi** [comment]
Yes, but not with the given instructions. Renesas has moved away from the cloud solution presented here.

Please contact your Renesas representative for details on how to use the board without the cloud application.

**Comment by rzr** [comment]
Thx for the hint, I pinged them on twitter maybe I should try elsewhere like renesas rules forum

https://twitter.com/RzrFreeFr/status/1198915622542991361
